### PR TITLE
add component apple prods and create auth user and add deatiles prods…

### PR DESCRIPTION
**Pull request by Ahmedhassanin12**
… comp

### CODE REVIEW

**Review by GeorgeAtefMetry — COMMENTED** [review]
ok

**Review by Ahmedhassanin12 — COMMENTED** [review]
ok

**Comment by GeorgeAtefMetry** [comment]
ok

**Review by GeorgeAtefMetry — APPROVED** [review]
ok

**Comment by Ahmedhassanin12** [comment]
com

**Pull request closed without merging**
